
version: '3'

x-env-variables: &env-variables
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: "egov"
  DATABASE_URL: ""

services:

  db:
    container_name: postgresql_db
    image: postgres
    ports:
      - 5433:5432
    environment: 
      <<: *env-variables

  backend:
    container_name: fastapi_app
    environment: 
      <<: *env-variables
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ["./docker/app.sh"]
    depends_on:
      - db
    

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

